version: '3'

services:

  realtyna_db:
    container_name: realtyna_db
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - realtyna_db:/var/lib/postgresql/data

  realtyna_api:
    container_name: realtyna_api
    build: .
    restart: unless-stopped
    depends_on:
      - realtyna_db
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 9052:80
    command: ["python", "/app/realtyna/manage.py", "runserver", "0:80"]
    environment:
      DEBUG: 'True'

volumes:
  realtyna_db:
